'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class agendamientos
    Public Property id As Integer
    Public Property fechaInicio As Date
    Public Property fechaFin As Date
    Public Property horaInicio As System.TimeSpan
    Public Property horaFin As System.TimeSpan
    Public Property id_Usuario As Integer
    Public Property id_Empresa As Integer
    Public Property estado As Nullable(Of Boolean)

    Public Overridable Property agendamientos_detalles As ICollection(Of agendamientos_detalles) = New HashSet(Of agendamientos_detalles)
    Public Overridable Property empresas As empresas
    Public Overridable Property usuarios As usuarios
    Public Overridable Property pagos As ICollection(Of pagos) = New HashSet(Of pagos)

End Class
