'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class agendamientos_detalles
    Public Property id As Integer
    Public Property id_Agendamiento As Nullable(Of Integer)
    Public Property id_Espacio As Nullable(Of Integer)
    Public Property id_Profesional As Nullable(Of Integer)
    Public Property id_Producto As Nullable(Of Integer)
    Public Property estado As Nullable(Of Boolean)

    Public Overridable Property agendamientos As agendamientos
    Public Overridable Property espacios As espacios
    Public Overridable Property profesionales As profesionales
    Public Overridable Property productos As productos

End Class
