'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class empresas
    Public Property id As Integer
    Public Property identificacion As String
    Public Property nombre As String
    Public Property razonSocial As String
    Public Property tipo As String
    Public Property direccion As String
    Public Property telefono As String
    Public Property logo As String
    Public Property correoElectronico As String
    Public Property estado As Nullable(Of Boolean)

    Public Overridable Property agendamientos As ICollection(Of agendamientos) = New HashSet(Of agendamientos)
    Public Overridable Property espacios As ICollection(Of espacios) = New HashSet(Of espacios)
    Public Overridable Property parametros As ICollection(Of parametros) = New HashSet(Of parametros)
    Public Overridable Property productos As ICollection(Of productos) = New HashSet(Of productos)
    Public Overridable Property profesionales As ICollection(Of profesionales) = New HashSet(Of profesionales)
    Public Overridable Property suscripciones As ICollection(Of suscripciones) = New HashSet(Of suscripciones)
    Public Overridable Property usuarios As ICollection(Of usuarios) = New HashSet(Of usuarios)

End Class
