'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class pagos
    Public Property id As Integer
    Public Property id_Agendamiento As Integer
    Public Property valor As Decimal
    Public Property saldo As Decimal
    Public Property estado As Nullable(Of Boolean)

    Public Overridable Property agendamientos As agendamientos

End Class
