'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class parametros
    Public Property id As Integer
    Public Property solicitarPago As Nullable(Of Boolean)
    Public Property porcentajePago As Nullable(Of Decimal)
    Public Property tiempoReagendamiento As Nullable(Of Integer)
    Public Property tiempoCancelancion As Nullable(Of Integer)
    Public Property multaCancelacion As Nullable(Of Boolean)
    Public Property porcentajeCancelacion As Nullable(Of Decimal)
    Public Property cantidadAforo As Integer
    Public Property id_Empresa As Integer
    Public Property estado As Nullable(Of Boolean)

    Public Overridable Property empresas As empresas

End Class
