'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class profesionales
    Public Property id As Integer
    Public Property identificacion As String
    Public Property nombre As String
    Public Property id_Empresa As Integer
    Public Property estado As Nullable(Of Boolean)

    Public Overridable Property agendamientos_detalles As ICollection(Of agendamientos_detalles) = New HashSet(Of agendamientos_detalles)
    Public Overridable Property disponibilidad As ICollection(Of disponibilidad) = New HashSet(Of disponibilidad)
    Public Overridable Property empresas As empresas

End Class
