'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class usuarios
    Public Property id As Integer
    Public Property identificacion As String
    Public Property nombre As String
    Public Property apellido As String
    Public Property correoElectronico As String
    Public Property contrasenia As Byte()
    Public Property tipo As Nullable(Of Integer)
    Public Property direccion As String
    Public Property id_Empresa As Integer
    Public Property estado As Nullable(Of Boolean)

    Public Overridable Property agendamientos As ICollection(Of agendamientos) = New HashSet(Of agendamientos)
    Public Overridable Property empresas As empresas

End Class
