//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class disponibilidad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public disponibilidad()
        {
            this.pagos = new HashSet<pagos>();
        }
    
        public int id { get; set; }
        public int id_DisponibilidadEmpresa { get; set; }
        public int id_Usuario { get; set; }
        public Nullable<int> id_Espacio { get; set; }
        public Nullable<int> id_Profesional { get; set; }
        public Nullable<int> id_Producto { get; set; }
        public int id_Empresa { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual disponibilidad_empresa disponibilidad_empresa { get; set; }
        public virtual empresas empresas { get; set; }
        public virtual espacios espacios { get; set; }
        public virtual profesionales profesionales { get; set; }
        public virtual productos productos { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagos> pagos { get; set; }
    }
}
