//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pagos
    {
        public int id { get; set; }
        public int id_Disponibilidad { get; set; }
        public decimal valor { get; set; }
        public decimal saldo { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual disponibilidad disponibilidad { get; set; }
    }
}
