//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class suscripciones
    {
        public int id { get; set; }
        public int id_Empresa { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public int id_Plan { get; set; }
        public Nullable<bool> estado { get; set; }
    
        public virtual empresas empresas { get; set; }
        public virtual planes planes { get; set; }
    }
}
